### ISSUE TITLE
Guard Bot Ignoring Stay Order

### ISSUE THREAD

**Issue by Subw00fer** [drewcifer/bot-topia#2]
**Describe the bug**
The bug is thus: that the guard bot, after being told to "stay", will ignore said order after an indeterminate amount of time as a result of unknown stimuli.

**To Reproduce**
1. Set guard bot as "stay."
2. Walk away about 7-12 chunks or so and wait for around 8-12 minutes.
3. *Unknown stimuli.*
4. Guard bot teleports to you in "follow" state.

**Expected behavior**
What's supposed to happen is that the guard bot, after being told to "stay," should stay where it's put, presumably wandering to engage hostile mobs as they enter it's attack radius.

**Screenshots**
Late at night and getting to bed, thus no screenshots.

**Minecraft**
 
 - Version 1.16.201

**Bot-Topia**
- Version 1.0.6

**Additional context**
It is possible that, by engaging hostile mobs, its sit order is repealed when the bot owner is a sufficient distance away while still in entity render distance. Further testing required.

**Comment by drewcifer** [comment]
https://minecraft.gamepedia.com/Sitting

It's like the wolf. So when a wolf is tamed it doesn't really attack things unless you attack first or are attacked first, with a few exceptions. The guard bots on the other hand will attack any baddies that come near them. That's the reason it is the way it is. But I can see how that can be annoying. Since this is kind of default behavior for minecraft there may be ways around it. Worth looking into.

**Comment by Subw00fer** [comment]
> https://minecraft.gamepedia.com/Sitting
> 
> "It's like the wolf. So when a wolf is tamed it doesn't really attack things unless you attack first or are attacked first, with a few exceptions. The guard bots on the other hand will attack any baddies that come near them. That's the reason it is the way it is."

You may be misunderstanding. The issue is not that it is attacking while in "stay," the issue is that it seems to be going from "stay" to "follow the owner and teleport to them" after it attacks, instead of staying in the area it is "stay'd" in.

**Comment by drewcifer** [comment]
I understand. What I'm saying is to keep them from teleporting we would have to remove their behavior that makes them attack hostile mobs that the player has not attacked yet. 

- So it's a trade off. Either the guard bot defends the player before the player attacks or is attacked by a hostile mob. This is what causes the guard bot to teleport after you tell it to sit.
- Or the guard bot only attacks mobs that has attacked the player or the player attacks. This will keep the bots from teleporting after you tell it to sit. but the guard bot wont really be guarding when in sit.

One alternative I've thought of is adding a family to the guard bot that will make hostile mobs hostile to the bot... but the results would be the same... if the guard bot is attacked while sitting and attempts to defend itself it would still teleport.


I'm keeping this issue open for now because It think it deserves some discussion.
